#ifndef LIBUC_TEST_ARCH_AARCH64_REGISTER_PROBE_H
#define LIBUC_TEST_ARCH_AARCH64_REGISTER_PROBE_H

#include "fiber/fiber.h"

/* Trash every callee-saved register and suspend before any epilogue can
 * repair them. */
[[gnu::naked]] [[maybe_unused]] static void dirty_registers_and_yield(void) {
  __asm__ volatile("stp x29, x30, [sp, #-0xa0]!\n"
                   "stp x19, x20, [sp, #0x10]\n"
                   "stp x21, x22, [sp, #0x20]\n"
                   "stp x23, x24, [sp, #0x30]\n"
                   "stp x25, x26, [sp, #0x40]\n"
                   "stp x27, x28, [sp, #0x50]\n"
                   "stp d8, d9, [sp, #0x60]\n"
                   "stp d10, d11, [sp, #0x70]\n"
                   "stp d12, d13, [sp, #0x80]\n"
                   "stp d14, d15, [sp, #0x90]\n"

                   "mov x19, #0xdead\n"
                   "mov x20, #0xdead\n"
                   "mov x21, #0xdead\n"
                   "mov x22, #0xdead\n"
                   "mov x23, #0xdead\n"
                   "mov x24, #0xdead\n"
                   "mov x25, #0xdead\n"
                   "mov x26, #0xdead\n"
                   "mov x27, #0xdead\n"
                   "mov x28, #0xdead\n"
                   "fmov d8, x19\n"
                   "fmov d9, x19\n"
                   "fmov d10, x19\n"
                   "fmov d11, x19\n"
                   "fmov d12, x19\n"
                   "fmov d13, x19\n"
                   "fmov d14, x19\n"
                   "fmov d15, x19\n"
                   "bl __libuc_fiber_yield\n"

                   "ldp x19, x20, [sp, #0x10]\n"
                   "ldp x21, x22, [sp, #0x20]\n"
                   "ldp x23, x24, [sp, #0x30]\n"
                   "ldp x25, x26, [sp, #0x40]\n"
                   "ldp x27, x28, [sp, #0x50]\n"
                   "ldp d8, d9, [sp, #0x60]\n"
                   "ldp d10, d11, [sp, #0x70]\n"
                   "ldp d12, d13, [sp, #0x80]\n"
                   "ldp d14, d15, [sp, #0x90]\n"
                   "ldp x29, x30, [sp], #0xa0\n"
                   "ret\n");
}

/* Load a distinct sentinel into every callee-saved register, resume the
 * fiber through one suspension, and report the first register that came
 * back changed: 1..10 for x19..x28, 11..18 for d8..d15, 0 when all
 * survived. */
[[gnu::naked]] [[maybe_unused]] static unsigned long
run_probing_registers(struct __libuc_fiber *fiber) {
  __asm__ volatile("stp x29, x30, [sp, #-0xb0]!\n"
                   "mov x29, sp\n"
                   "stp x19, x20, [sp, #0x10]\n"
                   "stp x21, x22, [sp, #0x20]\n"
                   "stp x23, x24, [sp, #0x30]\n"
                   "stp x25, x26, [sp, #0x40]\n"
                   "stp x27, x28, [sp, #0x50]\n"
                   "stp d8, d9, [sp, #0x60]\n"
                   "stp d10, d11, [sp, #0x70]\n"
                   "stp d12, d13, [sp, #0x80]\n"
                   "stp d14, d15, [sp, #0x90]\n"
                   "str x0, [sp, #0xa0]\n"

                   "mov x19, #0xb001\n"
                   "mov x20, #0xb002\n"
                   "mov x21, #0xb003\n"
                   "mov x22, #0xb004\n"
                   "mov x23, #0xb005\n"
                   "mov x24, #0xb006\n"
                   "mov x25, #0xb007\n"
                   "mov x26, #0xb008\n"
                   "mov x27, #0xb009\n"
                   "mov x28, #0xb00a\n"
                   "mov x9, #0xd001\n"
                   "fmov d8, x9\n"
                   "mov x9, #0xd002\n"
                   "fmov d9, x9\n"
                   "mov x9, #0xd003\n"
                   "fmov d10, x9\n"
                   "mov x9, #0xd004\n"
                   "fmov d11, x9\n"
                   "mov x9, #0xd005\n"
                   "fmov d12, x9\n"
                   "mov x9, #0xd006\n"
                   "fmov d13, x9\n"
                   "mov x9, #0xd007\n"
                   "fmov d14, x9\n"
                   "mov x9, #0xd008\n"
                   "fmov d15, x9\n"

                   "ldr x0, [sp, #0xa0]\n"
                   "bl __libuc_fiber_resume\n"

                   "mov x0, #1\n"
                   "mov x9, #0xb001\n"
                   "cmp x19, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #2\n"
                   "mov x9, #0xb002\n"
                   "cmp x20, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #3\n"
                   "mov x9, #0xb003\n"
                   "cmp x21, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #4\n"
                   "mov x9, #0xb004\n"
                   "cmp x22, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #5\n"
                   "mov x9, #0xb005\n"
                   "cmp x23, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #6\n"
                   "mov x9, #0xb006\n"
                   "cmp x24, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #7\n"
                   "mov x9, #0xb007\n"
                   "cmp x25, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #8\n"
                   "mov x9, #0xb008\n"
                   "cmp x26, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #9\n"
                   "mov x9, #0xb009\n"
                   "cmp x27, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #10\n"
                   "mov x9, #0xb00a\n"
                   "cmp x28, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #11\n"
                   "mov x9, #0xd001\n"
                   "fmov x10, d8\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #12\n"
                   "mov x9, #0xd002\n"
                   "fmov x10, d9\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #13\n"
                   "mov x9, #0xd003\n"
                   "fmov x10, d10\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #14\n"
                   "mov x9, #0xd004\n"
                   "fmov x10, d11\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #15\n"
                   "mov x9, #0xd005\n"
                   "fmov x10, d12\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #16\n"
                   "mov x9, #0xd006\n"
                   "fmov x10, d13\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #17\n"
                   "mov x9, #0xd007\n"
                   "fmov x10, d14\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #18\n"
                   "mov x9, #0xd008\n"
                   "fmov x10, d15\n"
                   "cmp x10, x9\n"
                   "b.ne 9f\n"
                   "mov x0, #0\n"

                   "9:\n"
                   "ldp x19, x20, [sp, #0x10]\n"
                   "ldp x21, x22, [sp, #0x20]\n"
                   "ldp x23, x24, [sp, #0x30]\n"
                   "ldp x25, x26, [sp, #0x40]\n"
                   "ldp x27, x28, [sp, #0x50]\n"
                   "ldp d8, d9, [sp, #0x60]\n"
                   "ldp d10, d11, [sp, #0x70]\n"
                   "ldp d12, d13, [sp, #0x80]\n"
                   "ldp d14, d15, [sp, #0x90]\n"
                   "ldp x29, x30, [sp], #0xb0\n"
                   "ret\n");
}

#endif
